version: '3.8'

services:
  app:
    image: shopping_platform  # ใช้ image ที่มีชื่อว่า senior_project
    build:
      context: .  # ใช้ context เป็น parent directory ของโปรเจค
      dockerfile: Dockerfile  # ตั้งค่าตำแหน่ง Dockerfile ที่ใช้ในการ build
    container_name: shopping_platform  # ตั้งชื่อคอนเทนเนอร์เป็น main_server
    ports:
      - "55543:55543" 

    volumes:
      - ../:/app  # แชร์โฟลเดอร์โปรเจคจากโฮสต์ไปยังคอนเทนเนอร์ที่ /app
      - /app/node_modules  # เพื่อไม่ให้ /app/node_modules ถูกทับด้วยข้อมูลจากโฟลเดอร์โปรเจค
    environment:
      - NODE_ENV=production  # ตั้งค่า environment variable สำหรับโหมด production
    env_file:
      - .env  # โหลด environment variables จากไฟล์ .env ที่อยู่ใน root directory ของโปรเจค
    networks:
      - shopping_platform_net  # เชื่อมต่อคอนเทนเนอร์กับ network ชื่อ shopping_platform_net

networks:
  shopping_platform_net:
    driver: bridge  # ใช้ network driver แบบ bridge